version: 2.0.{build}

environment: 
  build_options: 'alpha'

build_script:
- ps: nuget pack CSharpRuleSet.nuspec -Version $env:APPVEYOR_BUILD_VERSION -Suffix $(If ($env:build_options) {$env:build_options} Else {""})
test: off
artifacts:
- path: '**\*.nupkg'

for:
-
 branches:
   only:
   - master
   
 environment:
   build_options: ''